"""
Django settings for mpmat project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'am+c2iikd1pch2iq4h#e00gyj41y8h%5)x6(j6toe_vc$w^s$8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'material',
    'material.frontend',
    # 'material.admin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 'examples.employees.apps.EmployeesConfig',
    # 'integration.apps.IntegrationAppConfig',
    # 'sales'
    'mp08',
    'myprofile',
    'relatedwidget',
    'todolist',
    'sitetree',
    'somedemo',

    'fobi',
    'fobi.contrib.themes.bootstrap3', # Bootstrap 3 theme'
    'django_addanother',

    'mpdraft'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mpmat.urls'
LOGIN_REDIRECT_URL = '/admin/'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'material.frontend.context_processors.modules',
                'fobi.context_processors.theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'mpmat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'dbmp.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# shortcut for in form templates
# try:
#     # shortcut for in form templates
#     from django.template.base import add_to_builtins
#     add_to_builtins('material.templatetags.material_form')
#     # add_to_builtins('template_debug.templatetags.debug_tags')
# except ImportError:
#     """
#     Django 1.9.
#     """
#     TEMPLATES[0]['OPTIONS']['builtins'] = [
#         'material.templatetags.material_form',
#         # 'template_debug.templatetags.debug_tags'
#     ]

PROJECT_DIR=os.path.dirname(__file__)

STATICFILES_DIRS= (os.path.join(BASE_DIR, 'static'), )

STATIC_ROOT = os.path.join(PROJECT_DIR,'static/',)

PROJECT_PATH = os.path.join(PROJECT_DIR,'static/')


MEDIA_ROOT=os.path.join(BASE_DIR,'uploads')
MEDIA_URL = '/media/'


#имена привязок для страниц входа и выхода
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'