# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somedemo', '0004_historicalsimplepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsimplepage',
            name='categoty',
        ),
        migrations.RemoveField(
            model_name='historicalsimplepage',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalSimplePage',
        ),
    ]
