# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-28 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=24, verbose_name='Номер договора')),
                ('student_home_phone', models.CharField(max_length=180, verbose_name='домашний телефон студента')),
            ],
        ),
        migrations.CreateModel(
            name='FioChange',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='дата создания фио')),
                ('fio', models.CharField(max_length=120, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=6, verbose_name='пол')),
                ('doc', models.CharField(max_length=240, verbose_name='doc')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Citizenship', verbose_name='гражданство')),
                ('parent_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_document', to='student.CertificateType', verbose_name='документ родителей')),
                ('student_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_document', to='student.CertificateType', verbose_name='документ студента')),
            ],
        ),
        migrations.AddField(
            model_name='fiochange',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='студент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student', verbose_name='студента'),
        ),
    ]
