# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp08', '0002_auto_20170901_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodmp',
            name='package',
        ),
        migrations.AddField(
            model_name='packagemp',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mp08.MethodMp'),
        ),
    ]
