# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp08', '0005_auto_20170901_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemp',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='mp08.MethodMp'),
        ),
    ]
