# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp08', '0007_generalworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('snils', models.CharField(max_length=255)),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp08.PackageMp')),
            ],
            options={
                'verbose_name': 'Физтческое лицо',
            },
        ),
    ]
